services:
  postgres:
    image: postgres:17
    container_name: phoenix-fit-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: phoenix_fit
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: phoenix_fit
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
